import collections
import dataclasses
import datetime
import logging
import math
import pathlib
import re

import imageio
from libero.libero import benchmark
from libero.libero import get_libero_path
from libero.libero.envs import OffScreenRenderEnv
import numpy as np
from openpi_client import image_tools
from openpi_client import websocket_client_policy as _websocket_client_policy
from semantic_utils import load_semantic_manifest
from semantic_utils import rewrite_instruction
import tqdm
import tyro

LIBERO_DUMMY_ACTION = [0.0] * 6 + [-1.0]
LIBERO_ENV_RESOLUTION = 256  # resolution used to render training data


@dataclasses.dataclass
class Args:
    #################################################################################################################
    # Model server parameters
    #################################################################################################################
    host: str = "0.0.0.0"
    port: int = 8000
    resize_size: int = 224
    replan_steps: int = 5

    #################################################################################################################
    # LIBERO environment-specific parameters
    #################################################################################################################
    task_suite_name: str = (
        "libero_spatial"  # Task suite. Options: libero_spatial, libero_object, libero_goal, libero_10, libero_90
    )
    perturbation_type: str = "semantic"  # Options: semantic, position, object, goal
    perturbation_variant: str = ""  # Generic variant selector; for position perturbation only 'shift' is supported
    semantic_variant: str = "paraphrase"  # Options: none, paraphrase, constraint, reference, noisy
    semantic_manifest: str = "libero_data/libero_semantic_enhanced/instruction_variants.json"  # Optional JSON generated by scripts/build_libero_semantic_bddl.py
    bddl_root_override: str = "third_party/libero/libero/libero/bddl_files_multiperturbation"  # Optional root path, e.g. third_party/libero/libero/libero/bddl_files_semantic
    num_steps_wait: int = 10  # Number of steps to wait for objects to stabilize i n sim
    num_trials_per_task: int = 20  # Number of rollouts per task

    #################################################################################################################
    # Utils
    #################################################################################################################
    video_out_path: str = "data/libero"  # Base path; videos are saved to {video_out_path}/{semantic_variant}

    seed: int = 7  # Random Seed (for reproducibility)


def eval_libero(args: Args) -> None:
    # Set random seed
    np.random.seed(args.seed)

    # Initialize LIBERO task suite
    benchmark_dict = benchmark.get_benchmark_dict()
    task_suite = benchmark_dict[args.task_suite_name]()
    num_tasks_in_suite = task_suite.n_tasks
    selected_variant = _selected_variant(args)
    logging.info(
        "Task suite: %s, perturbation: %s/%s",
        args.task_suite_name,
        args.perturbation_type,
        selected_variant,
    )
    semantic_manifest = load_semantic_manifest(args.semantic_manifest)

    video_out_dir = pathlib.Path(args.video_out_path) / args.perturbation_type / args.task_suite_name / selected_variant
    video_out_dir.mkdir(parents=True, exist_ok=True)

    if args.task_suite_name == "libero_spatial":
        max_steps = 220  # longest training demo has 193 steps
    elif args.task_suite_name == "libero_object":
        max_steps = 280  # longest training demo has 254 steps
    elif args.task_suite_name == "libero_goal":
        max_steps = 300  # longest training demo has 270 steps
    elif args.task_suite_name == "libero_10":
        max_steps = 520  # longest training demo has 505 steps
    elif args.task_suite_name == "libero_90":
        max_steps = 400  # longest training demo has 373 steps
    else:
        raise ValueError(f"Unknown task suite: {args.task_suite_name}")

    client = _websocket_client_policy.WebsocketClientPolicy(args.host, args.port)

    # Start evaluation
    total_episodes, total_successes = 0, 0
    for task_id in tqdm.tqdm(range(num_tasks_in_suite)):
        # Get task
        task = task_suite.get_task(task_id)
        task_bddl_file = _resolve_task_bddl_file(task, args)
        if args.perturbation_type == "semantic":
            task_description = rewrite_instruction(task.language, selected_variant, semantic_manifest)
        else:
            task_description = _read_language_from_bddl(task_bddl_file, task.language)

        # Get default LIBERO initial states
        initial_states = task_suite.get_task_init_states(task_id)

        # Initialize LIBERO environment and task description
        env = _get_libero_env(task_bddl_file, LIBERO_ENV_RESOLUTION, args.seed)

        # Start episodes
        task_episodes, task_successes = 0, 0
        for episode_idx in tqdm.tqdm(range(args.num_trials_per_task)):
            logging.info(f"\nTask: {task_description}")

            # Reset environment
            # NOTE: For position perturbation, we must NOT call set_init_state after reset.
            # The pre-recorded initial_states were generated from the original (unperturbed)
            # BDDL. set_init_state restores sim.data.qpos for movable objects (bowl, plate,
            # etc.) to those old positions, while fixtures (flat_stove_1 etc.) remain at
            # the shifted positions set by sim.model.body_pos during reset. This mismatch
            # causes the bowl to end up at the original stove location instead of on the
            # shifted stove. For position perturbation, rely solely on the BDDL-based
            # placement from env.reset().
            obs = env.reset()
            action_plan = collections.deque()

            # Set initial states for perturbation types that do not change object placements.
            # Position perturbation shifts region coordinates, so pre-recorded states are invalid.
            # Object perturbation adds or changes objects, making pre-recorded state dimensions or contents invalid.
            if args.perturbation_type not in ("position", "object"):
                obs = env.set_init_state(initial_states[episode_idx])

            # Setup
            t = 0
            replay_images = []

            logging.info(f"Starting episode {task_episodes+1}...")
            while t < max_steps + args.num_steps_wait:
                try:
                    # IMPORTANT: Do nothing for the first few timesteps because the simulator drops objects
                    # and we need to wait for them to fall
                    if t < args.num_steps_wait:
                        obs, reward, done, info = env.step(LIBERO_DUMMY_ACTION)
                        t += 1
                        continue

                    # Get preprocessed image
                    # IMPORTANT: rotate 180 degrees to match train preprocessing
                    img = np.ascontiguousarray(obs["agentview_image"][::-1, ::-1])
                    wrist_img = np.ascontiguousarray(obs["robot0_eye_in_hand_image"][::-1, ::-1])
                    img = image_tools.convert_to_uint8(
                        image_tools.resize_with_pad(img, args.resize_size, args.resize_size)
                    )
                    wrist_img = image_tools.convert_to_uint8(
                        image_tools.resize_with_pad(wrist_img, args.resize_size, args.resize_size)
                    )

                    # Save preprocessed image for replay video
                    replay_images.append(img)

                    if not action_plan:
                        # Finished executing previous action chunk -- compute new chunk
                        # Prepare observations dict
                        element = {
                            "observation/image": img,
                            "observation/wrist_image": wrist_img,
                            "observation/state": np.concatenate(
                                (
                                    obs["robot0_eef_pos"],
                                    _quat2axisangle(obs["robot0_eef_quat"]),
                                    obs["robot0_gripper_qpos"],
                                )
                            ),
                            "prompt": str(task_description),
                        }

                        # Query model to get action
                        action_chunk = client.infer(element)["actions"]
                        assert (
                            len(action_chunk) >= args.replan_steps
                        ), f"We want to replan every {args.replan_steps} steps, but policy only predicts {len(action_chunk)} steps."
                        action_plan.extend(action_chunk[: args.replan_steps])

                    action = action_plan.popleft()

                    # Execute action in environment
                    obs, reward, done, info = env.step(action.tolist())
                    if done:
                        task_successes += 1
                        total_successes += 1
                        break
                    t += 1

                except Exception as e:
                    logging.error(f"Caught exception: {e}")
                    break

            task_episodes += 1
            total_episodes += 1

            # Save a replay video of the episode
            suffix = "success" if done else "failure"
            task_segment = pathlib.Path(task.bddl_file).stem
            imageio.mimwrite(
                video_out_dir / f"rollout_{task_segment}_{suffix}.mp4",
                [np.asarray(x) for x in replay_images],
                fps=10,
            )

            # Log current results
            logging.info(f"Success: {done}")
            logging.info(f"# episodes completed so far: {total_episodes}")
            logging.info(f"# successes: {total_successes} ({total_successes / total_episodes * 100:.1f}%)")

        # Log final results
        logging.info(f"Current task success rate: {float(task_successes) / float(task_episodes)}")
        logging.info(f"Current total success rate: {float(total_successes) / float(total_episodes)}")

    logging.info(f"Total success rate: {float(total_successes) / float(total_episodes)}")
    logging.info(f"Total episodes: {total_episodes}")


def _get_libero_env(task_bddl_file: pathlib.Path, resolution, seed):
    """Initializes and returns the LIBERO environment."""
    env_args = {"bddl_file_name": task_bddl_file, "camera_heights": resolution, "camera_widths": resolution}
    env = OffScreenRenderEnv(**env_args)
    env.seed(seed)  # IMPORTANT: seed seems to affect object positions even when using fixed initial state
    return env


def _read_language_from_bddl(bddl_path: pathlib.Path, fallback: str) -> str:
    """Read :language text from selected BDDL to keep policy prompt aligned with perturbations."""
    try:
        content = bddl_path.read_text(encoding="utf-8")
    except Exception:
        return fallback

    match = re.search(r"\(:language\s+([^\n\)]+)\)", content)
    if not match:
        return fallback
    text = match.group(1).strip()
    return text if text else fallback


def _resolve_task_bddl_file(task, args: Args) -> pathlib.Path:
    default_root = pathlib.Path(get_libero_path("bddl_files"))
    root = pathlib.Path(args.bddl_root_override) if args.bddl_root_override else default_root

    default_bddl_path = root / task.problem_folder / task.bddl_file
    selected_variant = _selected_variant(args)
    if selected_variant == "none":
        return default_bddl_path

    task_stem = pathlib.Path(task.bddl_file).stem
    candidate_names = []
    if args.perturbation_type == "semantic":
        candidate_names.append(f"{task_stem}__{selected_variant}.bddl")
        candidate_names.append(f"{task_stem}__semantic_{selected_variant}.bddl")
    else:
        candidate_names.append(f"{task_stem}__{args.perturbation_type}_{selected_variant}.bddl")

    for candidate_name in candidate_names:
        candidate_path = root / task.problem_folder / candidate_name
        if candidate_path.exists():
            return candidate_path

    logging.warning(
        "Perturbed BDDL not found for task %s with perturbation %s/%s under %s; falling back to %s",
        task.name,
        args.perturbation_type,
        selected_variant,
        root / task.problem_folder,
        default_bddl_path,
    )
    return default_bddl_path


def _selected_variant(args: Args) -> str:
    return args.perturbation_variant or args.semantic_variant


def _quat2axisangle(quat):
    """
    Copied from robosuite: https://github.com/ARISE-Initiative/robosuite/blob/eafb81f54ffc104f905ee48a16bb15f059176ad3/robosuite/utils/transform_utils.py#L490C1-L512C55
    """
    # clip quaternion
    if quat[3] > 1.0:
        quat[3] = 1.0
    elif quat[3] < -1.0:
        quat[3] = -1.0

    den = np.sqrt(1.0 - quat[3] * quat[3])
    if math.isclose(den, 0.0):
        # This is (close to) a zero degree rotation, immediately return
        return np.zeros(3)

    return (quat[:3] * 2.0 * math.acos(quat[3])) / den


if __name__ == "__main__":
    args = tyro.cli(Args)

    # Configure logging to both console and file
    log_dir = pathlib.Path("logs/libero")
    log_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.datetime.now(tz=datetime.UTC).strftime("%Y%m%d_%H%M%S")
    log_file = (
        log_dir / f"eval_{timestamp}_{args.task_suite_name}_{args.perturbation_type}_{_selected_variant(args)}.log"
    )

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[logging.FileHandler(log_file), logging.StreamHandler()],
    )
    logging.info(f"Logging to file: {log_file}")
    eval_libero(args)
